sudo: required
language: java
install: true
script: mvn clean package assembly:single
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: "anchel-client"
  local_dir: /home/travis/build/t3ctechnologies/Anchel_Client/target
  skip_cleanup: true
  