sudo: required
language: java
install: true
script: mvn clean package assembly:single
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "anchel-client"
  